# Generated by Django 5.2.1 on 2025-06-02 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_title', models.CharField(default='Hikayemiz', max_length=200, verbose_name='Hikaye Başlığı')),
                ('story_content', models.TextField(verbose_name='Hikaye İçeriği')),
                ('story_image', models.ImageField(blank=True, upload_to='about/', verbose_name='Hikaye Resmi')),
                ('years_experience', models.PositiveIntegerField(default=20, verbose_name='Yıllık Deneyim')),
                ('happy_customers', models.PositiveIntegerField(default=5000, verbose_name='Mutlu Müşteri')),
                ('product_varieties', models.PositiveIntegerField(default=30, verbose_name='Ürün Çeşidi')),
                ('cities_served', models.PositiveIntegerField(default=81, verbose_name='Hizmet Verilen İl')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hakkımızda Sayfası',
                'verbose_name_plural': 'Hakkımızda Sayfası',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Blog Kategorisi',
                'verbose_name_plural': 'Blog Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('icon_class', models.CharField(help_text='Font Awesome icon class (örn: fas fa-medal)', max_length=50, verbose_name='İkon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Şirket Değeri',
                'verbose_name_plural': 'Şirket Değerleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(choices=[('info', 'Ürün Bilgisi'), ('quote', 'Fiyat Teklifi'), ('support', 'Teknik Destek'), ('complaint', 'Şikayet'), ('other', 'Diğer')], max_length=20, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('is_replied', models.BooleanField(default=False, verbose_name='Cevaplandı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Soru')),
                ('answer', models.TextField(verbose_name='Cevap')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sık Sorulan Soru',
                'verbose_name_plural': 'Sık Sorulan Sorular',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Alt Başlık')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Resim')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Buton Yazısı')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='Buton Linki')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Slider',
                'verbose_name_plural': 'Ana Sayfa Slider',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Abone Tarihi')),
            ],
            options={
                'verbose_name': 'Bülten Abonesi',
                'verbose_name_plural': 'Bülten Aboneleri',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='Kategori Resmi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Ürün Kategorisi',
                'verbose_name_plural': 'Ürün Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='2M ISTANBUL ELEKTRONİK', max_length=100)),
                ('site_description', models.TextField(default='Para sayma makineleri ve çözümleri için güvenilir adres')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('phone_primary', models.CharField(default='+90 123 456 78 90', max_length=20)),
                ('phone_secondary', models.CharField(blank=True, max_length=20)),
                ('email_primary', models.EmailField(default='info@2mistanbul.com', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(default='Merkez Mah. Atatürk Cad. No:123 Kat:5, İstanbul')),
                ('working_hours_weekday', models.CharField(default='09:00 - 18:00', max_length=50)),
                ('working_hours_saturday', models.CharField(default='09:00 - 15:00', max_length=50)),
                ('working_hours_sunday', models.CharField(default='Kapalı', max_length=50)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('google_analytics', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('client_title', models.CharField(max_length=100, verbose_name='Ünvan/Şirket')),
                ('client_photo', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Müşteri Fotoğrafı')),
                ('content', models.TextField(verbose_name='Yorum İçeriği')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='Puan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Müşteri Yorumu',
                'verbose_name_plural': 'Müşteri Yorumları',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField(max_length=300, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('featured_image', models.ImageField(upload_to='blog/', verbose_name='Öne Çıkan Resim')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Resim Alt Text')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama')),
                ('keywords', models.CharField(blank=True, max_length=200, verbose_name='Anahtar Kelimeler')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.blogcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ürün Adı')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('short_description', models.CharField(max_length=300, verbose_name='Kısa Açıklama')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fiyat')),
                ('features', models.TextField(help_text='Her satıra bir özellik yazın', verbose_name='Özellikler')),
                ('technical_specs', models.TextField(blank=True, verbose_name='Teknik Özellikler')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ana Resim')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Resim Alt Text')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('in_stock', models.BooleanField(default=True, verbose_name='Stokta')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='Meta Başlık')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Açıklama')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.productcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
